### ISSUE TITLE
template error while templating string: no test named 'true'

### ISSUE THREAD

**Issue by mrzor** [clickfreak/ansible-fluentd-role#1]
https://github.com/clickfreak/ansible-fluentd-role/blob/master/tasks/main.yml#L14

Did you mean `is defined`? 

`is true` seems redundant to me - [Conditionals doc](http://docs.ansible.com/playbooks_conditionals.html) - maybe `- fluentd_sysctl_tuning` on this line would be enough.

I'm using Ansible 1.8.2

**Comment by norbu09** [comment]
ran into the same issue today when running against a vagrant image backed by VirtualBox running a precise32 image (http://files.vagrantup.com/precise32.box):

```
TASK: [clickfreak.fluentd | sysctl tuning] ************************************
fatal: [192.168.33.123] => template error while templating string: no test named 'true'
```

```
$ ansible --version
ansible 1.8.2
  configured module search path = None
```
